name: todo
description: Todo application using a clean architecture
publish_to: "none"

# major.minor.patch+YYYYMMDDNN (NN - build number. flush every day)
version: 1.0.0+2023113001

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # DI
  provider: ^6.1.1

  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  elementary: ^3.0.0

  # Models
  dart_mappable: ^4.0.1

  # Utils
  equatable: ^2.0.5
  elementary_helper: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  dart_mappable_builder: ^4.0.1

flutter:
  uses-material-design: true
